Implemented API endpoints  getUser, createUser, updateUser and deleteUser
Waleed-abdullah/IoT-Fuzzing-FYP pull request #11
Opened 2023-10-10 19:58 UTC by moezAhmad

### Description
Implementation of the user management API 

### Key  Changes:

**Password Hashing:** Implemented secure password storage by incorporating the bcrypt library, adhering to enterprise-level security standards.

**Ensuring Uniqueness:** Added checks to guarantee the uniqueness of usernames and emails within the system, preventing duplicate entries.

**Email and Password Format Validation:** Implemented a regular expression validation for email addresses and passwords to ensure they meet the required format.

**User Type Validation:** Incorporated a validation condition to ensure that the user_type field is limited to either "Waza Warrior" or "Waza Master."

GitHub Issue Link: Closes #10

2023-10-10 19:59 UTC, moezAhmad commented
@Waleed-abdullah kindly review

2023-10-11 17:38 UTC, Waleed-abdullah requested changes

2023-10-11 17:38 UTC, Waleed-abdullah commented on src/pages/api/index.ts
This file should be deleted

2023-10-11 17:38 UTC, Waleed-abdullah commented on src/pages/api/user/createUser.ts
> +
A user type object should be created for this, in lib/types.ts, Since we are using typescript we should be careful in creating and using types whenever possible to avoid any errors and produce good code.

2023-10-11 17:38 UTC, Waleed-abdullah commented on src/pages/layout.tsx
I think this is what is causing the build error kindly recheck it and fix it, I am not sure but I think app folder should contain this file

2023-10-11 18:28 UTC, moezAhmad commented on src/pages/api/user/createUser.ts
> +
I have defined types in individual endpoint files. For now there is no code duplication. I will migrate them if needed

2023-10-11 18:30 UTC, moezAhmad commented on src/pages/layout.tsx
I created a directory named `/src/app `and relocated the `layout.tsx` file into it. Locally, I was able to successfully build the project using the `npm run build` command. However, it appears that the build is failing when deploying to Vercel.

![image](https://github.com/Waleed-abdullah/Final-year-project/assets/89748992/ab90ca97-a3f9-4af6-b0c1-cb62fe509f20)

2023-10-18 16:54 UTC, Waleed-abdullah commented on src/pages/api/user/createUser.ts
> +
The above code was causing the build error, you were using the findUnique method previously, which expects only the primary key of the table to retrieve data, that is why it was erroring out, you can see what the error is by running 'npm run build', its okay its fixed now.

2023-10-18 16:57 UTC, Waleed-abdullah commented on src/pages/api/user/createUser.ts
> +
I don't know how it built successfully on your side, make sure you have the latest version of node installed and run npm i again

2023-10-18 17:03 UTC, Waleed-abdullah commented on src/pages/api/user/createUser.ts
> +import { NextApiRequest, NextApiResponse } from 'next';
on it

2023-10-18 17:04 UTC, Waleed-abdullah commented
But findUnique only accepts the primary key of the table, and here we need to search using another field, so I think for now this is fine, maybe try to search for an alternate option

2023-10-18 17:12 UTC, moezAhmad commented on src/pages/api/user/createUser.ts
> +
I'll look into it

2023-10-18 17:13 UTC, moezAhmad commented
> But findUnique only accepts the primary key of the table, and here we need to search using another field, so I think for now this is fine, maybe try to search for an alternate option

Ok I will search for an alternate option.
I think for now this pull request is ready to get merged.

2023-10-18 17:15 UTC, merged