Auth routes
Waleed-abdullah/IoT-Fuzzing-FYP pull request #26
Opened 2023-11-29 05:35 UTC by moezAhmad

### Description
**Implemented Authentication with Google OAuth and Credentials in auth_routes Branch**

This pull request introduces significant updates to the authentication system within our application, focusing on both Google OAuth and traditional sign-in with credentials. The changes are encapsulated in the auth_routes branch. Below are the key highlights of this update:

**Google OAuth Integration:** Integrated Google OAuth for user authentication. This approach simplifies the login process for users, leveraging their Google accounts for secure and quick access.

**Sign-In with Credentials:** Implemented the classic sign-in method where users can log in using their email and password. This ensures that users without a Google account or those preferring traditional login methods can access the application.

**Handling New Users in Google OAuth:** For new users signing up via Google OAuth, the system now prompts them to provide additional details necessary for creating a comprehensive database record. After this step, they are directed to create a waza account, ensuring that all users have complete and functional profiles.

**Waza Account Creation for Credential Sign-Ins:** In the case of users signing in with credentials, the system checks for the presence of a waza_id. If a waza_id is not found, indicating a new user, the application prompts the user to create a waza account. This process is based on the user's type and ensures that all users have associated waza accounts for complete functionality within the application.

### Related Issue
#20 

Reviewers
@Waleed-abdullah

2023-11-30 02:02 UTC, Waleed-abdullah commented
Kindly resolve these build issues
![image](https://github.com/Waleed-abdullah/Final-year-project/assets/68333922/0b62eaba-2950-4340-ac8f-df16030d8985)

2023-12-05 16:45 UTC, Waleed-abdullah requested changes

2023-12-05 16:45 UTC, Waleed-abdullah commented on src/pages/api/auth/[...nextauth].ts
> +        console.log(user);
```suggestion

```

2023-12-05 16:45 UTC, Waleed-abdullah commented on src/pages/api/auth/[...nextauth].ts
> +          console.log('user found password matched');
```suggestion
 
```

2023-12-05 16:45 UTC, Waleed-abdullah commented on src/pages/api/auth/[...nextauth].ts
> +      console.log(profile);
```suggestion
```

2023-12-05 16:45 UTC, Waleed-abdullah commented on src/pages/api/auth/[...nextauth].ts
> +        console.log(userInDb);
```suggestion
```

2023-12-06 10:25 UTC, moezAhmad commented
I have removed all console logs.

2023-12-08 06:42 UTC, Waleed-abdullah approved these changes

2023-12-08 06:42 UTC, merged