Chats
Waleed-abdullah/IoT-Fuzzing-FYP pull request #56
Opened 2024-05-08 03:16 UTC by moezAhmad

# Pull Request Template

## Description

**Provide a description of the changes you made in this PR**

- Add Github issue link:
  Make sure to use closing keywords

## Checklist

## Reviewers

Please request a review for this PR.

> Make sure to link an issue with this PR using closing keywords in the description or from the development tab

2024-05-11 08:07 UTC, Waleed-abdullah requested changes

2024-05-11 08:07 UTC, Waleed-abdullah commented on src/types/app/(private)/chat/index.ts
no need to add directories for teh entire path just create one meaningful subdirectory like types/chat/index.ts

2024-05-11 08:11 UTC, Waleed-abdullah requested changes

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/pages/api/message/send.ts
> +import { sendErrorResponse } from '../../../utils/errorHandler';
updat import to use @/utils

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/pages/api/message/request.ts
> +import { sendErrorResponse } from '../../../utils/errorHandler';
same import here

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/pages/api/message/deny.ts
> +import { sendErrorResponse } from '../../../utils/errorHandler';
same import here

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/pages/api/message/accept.ts
> +import { sendErrorResponse } from '../../../utils/errorHandler';
same import here

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/pages/api/message/accept.ts
prefer using app router api routes, they are exposed using route.ts file

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/components/MessageRequests/index.tsx
> +    await axios.post('/api/message/deny', { sender_id });
does this rerender properly

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/types/pusher.d.ts
move file to types/pusher/index.ts instead

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/components/TrainerCard.tsx
>          <div className='flex flex-row flex-start gap-2'>
shouldnt we show trainer iage here

2024-05-11 08:11 UTC, Waleed-abdullah commented on src/app/(private)/chat/[chat_id]/page.tsx
> +import Messages from '../../../../components/Messages';
update import to @/components/messages

2024-05-11 12:42 UTC, moezAhmad commented on src/components/MessageRequests/index.tsx
> +    await axios.post('/api/message/deny', { sender_id });
yes, new messages are displayed

2024-05-11 12:42 UTC, moezAhmad commented on src/app/warrior/trainer-marketplace/components/TrainerCard.tsx
>          <div className='flex flex-row flex-start gap-2'>
Updated

2024-05-12 06:56 UTC, Waleed-abdullah approved these changes
Restis good just update the requested changes and mege once done

2024-05-12 06:56 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/[user_id]/page.tsx
> +import { DetailedTrainer } from '../../../../types/marketplace';
again need @/type/ import, always use absolute imports when going more than one level down or up in the folder tree

2024-05-12 06:56 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/components/TrainerCard.tsx
> +import { Trainer } from '../../../../types/marketplace';
same here

2024-05-12 06:56 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/components/TrainerList.tsx
> +import { Trainer } from '../../../../types/marketplace';
same here, I assume vscode automatically updated these when you moved the file and you missed them

2024-05-12 06:56 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/context/TrainerFilterContext.tsx
> +import { TrainerFilters } from '../../../../types/marketplace';
same

2024-05-12 06:56 UTC, Waleed-abdullah commented on src/app/warrior/trainer-marketplace/services/trainerService.ts
> +import { TrainerFilters } from '../../../../types/marketplace';
```suggestion
import { TrainerFilters } from '@/types/marketplace';
```

2024-05-12 18:50 UTC, merged